# Assignment 1: Data Wrangling I
## NumPy & Pandas Fundamentals

**Name:** ___________ | **Class:** T.E. | **Roll No:** ___________

## Problem Statement

1. Create NumPy arrays (1D and 2D) and perform: array indexing, slicing, reshaping, mathematical operations (add, subtract, multiply, divide), statistical operations (mean, median, std, min, max), matrix multiplication and transpose.

2. Create Pandas Series and DataFrame from dictionaries, lists, and CSV files. Perform: display basic info (head, tail, describe, info), handle missing values (dropna, fillna), select rows/columns using loc and iloc, filter data based on conditions, sort and group data.

## Theory

**NumPy:** Core library for numerical computing in Python. Provides the ndarray — a fast, memory-efficient N-dimensional array object that enables vectorized operations (operations applied to entire arrays without Python loops).

**Pandas:** Built on top of NumPy. Provides two key data structures:
- **Series:** 1D labeled array (like a column in Excel)
- **DataFrame:** 2D labeled table (like a spreadsheet)

**Key Concepts:**
- **Vectorization:** Operations applied to entire arrays at once — much faster than Python loops
- **loc vs iloc:** `loc` uses index labels/names; `iloc` uses integer positions
- **NaN:** Missing values are represented as NaN; must be handled before ML models can use the data

In [1]:
# Step 1: Import Required Libraries
import numpy as np
import pandas as pd

print('NumPy version:', np.__version__)
print('Pandas version:', pd.__version__)

NumPy version: 2.2.6
Pandas version: 2.3.3

In [2]:
# Step 2: NumPy 1D Array — Creation, Indexing, Slicing
arr1d = np.array([10, 25, 35, 40, 55, 60, 75, 85, 90, 100])
print('1D Array:', arr1d)
print('Shape:', arr1d.shape)
print('First element arr1d[0]:', arr1d[0])
print('Last element arr1d[-1]:', arr1d[-1])
print('Slice [2:6]:', arr1d[2:6])
print('Slice [:5]:', arr1d[:5])
print('Boolean indexing (arr > 50):', arr1d[arr1d > 50])

1D Array: [ 10  25  35  40  55  60  75  85  90 100]
Shape: (10,)
First element arr1d[0]: 10
Last element arr1d[-1]: 100
Slice [2:6]: [35 40 55 60]
Slice [:5]: [10 25 35 40 55]
Boolean indexing (arr > 50): [ 55  60  75  85  90 100]

In [3]:
# Step 3: NumPy 2D Array — Creation, Indexing, Reshaping, Transpose
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('2D Array:\n', arr2d)
print('Shape:', arr2d.shape)
print('Row 0:', arr2d[0])
print('Column 1:', arr2d[:, 1])
print('Element [1,2]:', arr2d[1, 2])
print('Reshape to 1x9:\n', arr2d.reshape(1, 9))
print('Transpose:\n', arr2d.T)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Row 0: [1 2 3]
Column 1: [2 5 8]
Element [1,2]: 6
Reshape to 1x9:
 [[1 2 3 4 5 6 7 8 9]]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

In [4]:
# Step 4: Mathematical Operations
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print('a =', a)
print('b =', b)
print('Addition a+b:', a + b)
print('Subtraction a-b:', a - b)
print('Multiplication a*b:', a * b)
print('Division a/b:', a / b)
print('Power a**2:', a ** 2)
print('Square root sqrt(a):', np.sqrt(a))
print('Natural log log(a):', np.log(a))

a = [1 2 3 4 5]
b = [10 20 30 40 50]
Addition a+b: [11 22 33 44 55]
Subtraction a-b: [ -9 -18 -27 -36 -45]
Multiplication a*b: [ 10  40  90 160 250]
Division a/b: [0.1 0.1 0.1 0.1 0.1]
Power a**2: [ 1  4  9 16 25]
Square root sqrt(a): [1.         1.41421356 1.73205081 2.         2.23606798]
Natural log log(a): [0.         0.69314718 1.09861229 1.38629436 1.60943791]

In [5]:
# Step 5: Statistical Operations on NumPy Arrays
data = np.array([12, 18, 22, 25, 28, 30, 35, 40, 45, 100])
print('Data:', data)
print('Mean:', np.mean(data))
print('Median:', np.median(data))
print('Std Deviation:', np.std(data))
print('Variance:', np.var(data))
print('Min:', np.min(data))
print('Max:', np.max(data))
print('Sum:', np.sum(data))
print('25th Percentile:', np.percentile(data, 25))
print('75th Percentile:', np.percentile(data, 75))

Data: [ 12  18  22  25  28  30  35  40  45 100]
Mean: 35.5
Median: 29.0
Std Deviation: 23.47019386370722
Variance: 550.85
Min: 12
Max: 100
Sum: 355
25th Percentile: 22.75
75th Percentile: 38.75

In [6]:
# Step 6: Matrix Multiplication and Transpose
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print('Matrix A:\n', A)
print('Matrix B:\n', B)
print('A @ B (matrix product):\n', A @ B)
print('np.dot(A, B):\n', np.dot(A, B))
print('Element-wise A * B:\n', A * B)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
A @ B (matrix product):
 [[19 22]
 [43 50]]
np.dot(A, B):
 [[19 22]
 [43 50]]
Element-wise A * B:
 [[ 5 12]
 [21 32]]

In [7]:
# Step 7: Pandas Series Creation
s1 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print('Series from list with custom index:')
print(s1)
s2 = pd.Series({'apple': 3, 'banana': 5, 'orange': 2})
print('\nSeries from dictionary:')
print(s2)

Series from list with custom index:
a    10
b    20
c    30
d    40
dtype: int64

Series from dictionary:
apple     3
banana    5
orange    2
dtype: int64

In [8]:
# Step 8: DataFrame Creation from Dictionary
data_dict = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Age': [22, 25, 30, 28, 24],
    'Score': [85, 92, 78, 95, 88],
    'City': ['NYC', 'LA', 'Chicago', 'NYC', 'LA']
}
df = pd.DataFrame(data_dict)
print('DataFrame from dictionary:')
df

DataFrame from dictionary:

      Name  Age  Score     City
0    Alice   22     85      NYC
1      Bob   25     92       LA
2  Charlie   30     78  Chicago
3    Diana   28     95      NYC
4      Eve   24     88       LA

In [9]:
# Step 9: Load DataFrame from CSV File
df_csv = pd.read_csv('datasets/iris.csv')
print(f'Loaded from CSV — Shape: {df_csv.shape}')
print('\nFirst 5 rows (head):')
df_csv.head()

Loaded from CSV — Shape: (150, 5)

First 5 rows (head):

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [10]:
# Step 10: Basic DataFrame Information
print('=== df.info() ===')
df_csv.info()
print('\n=== df.describe() ===')
df_csv.describe()

=== df.info() ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

=== df.describe() ===

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [11]:
# Step 11: Handle Missing Values
df_missing = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 20, 30, np.nan, 50],
    'C': ['x', 'y', np.nan, 'z', np.nan]
})
print('Original DataFrame with missing values:')
print(df_missing)
print('\nMissing values count:')
print(df_missing.isnull().sum())
print('\nAfter dropna():')
print(df_missing.dropna())
print('\nAfter fillna() - mean for numeric, \'unknown\' for categorical:')
df_filled = df_missing.copy()
df_filled['A'] = df_filled['A'].fillna(df_filled['A'].mean())
df_filled['B'] = df_filled['B'].fillna(df_filled['B'].mean())
df_filled['C'] = df_filled['C'].fillna('unknown')
print(df_filled)

Original DataFrame with missing values:
     A     B    C
0  1.0   NaN    x
1  2.0  20.0    y
2  NaN  30.0  NaN
3  4.0   NaN    z
4  5.0  50.0  NaN

Missing values count:
A    1
B    2
C    2
dtype: int64

After dropna():
     A     B  C
1  2.0  20.0  y

After fillna() - mean for numeric, 'unknown' for categorical:

     A          B        C
0  1.0  33.333333        x
1  2.0  20.000000        y
2  3.0  30.000000  unknown
3  4.0  33.333333        z
4  5.0  50.000000  unknown

In [12]:
# Step 12: Selection Using loc and iloc
df_demo = pd.DataFrame({
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Printer'],
    'Price': [1200, 25, 75, 300, 150],
    'Stock': [50, 200, 150, 80, 60]
})
df_demo.index = ['P1', 'P2', 'P3', 'P4', 'P5']
print('DataFrame:')
print(df_demo)
print('\nloc[\'P1\'] — select by label:')
print(df_demo.loc['P1'])
print('\nloc[[\'P1\',\'P3\'], [\'Product\',\'Price\']]:')
print(df_demo.loc[['P1', 'P3'], ['Product', 'Price']])
print('\niloc[0] — select by integer position:')
print(df_demo.iloc[0])
print('\niloc[1:3, 0:2]:')
print(df_demo.iloc[1:3, 0:2])

DataFrame:
     Product  Price  Stock
P1    Laptop   1200     50
P2     Mouse     25    200
P3  Keyboard     75    150
P4   Monitor    300     80
P5   Printer    150     60

loc['P1'] — select by label:
Product    Laptop
Price        1200
Stock          50
Name: P1, dtype: object

loc[['P1','P3'], ['Product','Price']]:
     Product  Price
P1    Laptop   1200
P3  Keyboard     75

iloc[0] — select by integer position:
Product    Laptop
Price        1200
Stock          50
Name: P1, dtype: object

iloc[1:3, 0:2]:
     Product  Price
P2     Mouse     25
P3  Keyboard     75

In [13]:
# Step 13: Filter Data Based on Conditions
print('Products with Price > 100:')
print(df_demo[df_demo['Price'] > 100])
print('\nProducts with Stock between 50 and 150:')
print(df_demo[(df_demo['Stock'] >= 50) & (df_demo['Stock'] <= 150)])
print('\nProducts whose name starts with M:')
print(df_demo[df_demo['Product'].str.startswith('M')])

Products with Price > 100:
    Product  Price  Stock
P1   Laptop   1200     50
P4  Monitor    300     80
P5  Printer    150     60

Products with Stock between 50 and 150:
     Product  Price  Stock
P1    Laptop   1200     50
P3  Keyboard     75    150
P4   Monitor    300     80
P5   Printer    150     60

Products whose name starts with M:
    Product  Price  Stock
P2    Mouse     25    200
P4  Monitor    300     80

In [14]:
# Step 14: Sort and Group Data
print('Sorted by Price (descending):')
print(df_demo.sort_values('Price', ascending=False))
print('\n=== GROUPBY on Iris Dataset ===')
grouped = df_csv.groupby('species')
print('Mean values by species:')
print(grouped.mean(numeric_only=True))
print('\nCount per species:')
print(grouped.size())

Sorted by Price (descending):
     Product  Price  Stock
P1    Laptop   1200     50
P4   Monitor    300     80
P5   Printer    150     60
P3  Keyboard     75    150
P2     Mouse     25    200

=== GROUPBY on Iris Dataset ===
Mean values by species:
            sepal length (cm)  sepal width (cm)  petal length (cm)  \
species
setosa                  5.006             3.428              1.462
versicolor              5.936             2.770              4.260
virginica               6.588             2.974              5.552

            petal width (cm)
species
setosa                 0.246
versicolor             1.326
virginica              2.026

Count per species:
species
setosa        50
versicolor    50
virginica     50
dtype: int64

In [15]:
# Step 15: Summary
print('=' * 60)
print('ASSIGNMENT 1 — SUMMARY')
print('=' * 60)
print('NumPy: 1D/2D arrays, indexing, slicing, reshape, transpose')
print('NumPy: math ops (add, sub, mul, div, sqrt, log)')
print('NumPy: stats (mean, median, std, var, min, max, percentile)')
print('NumPy: matrix multiplication (@, dot)')
print()
print('Pandas: Series & DataFrame (from dict, list, CSV)')
print('Pandas: head(), tail(), info(), describe()')
print('Pandas: isnull(), dropna(), fillna()')
print('Pandas: loc[], iloc[] for selection')
print('Pandas: Boolean filtering, sort_values(), groupby()')

============================================================
ASSIGNMENT 1 — SUMMARY
============================================================
NumPy: 1D/2D arrays, indexing, slicing, reshape, transpose
NumPy: math ops (add, sub, mul, div, sqrt, log)
NumPy: stats (mean, median, std, var, min, max, percentile)
NumPy: matrix multiplication (@, dot)

Pandas: Series & DataFrame (from dict, list, CSV)
Pandas: head(), tail(), info(), describe()
Pandas: isnull(), dropna(), fillna()
Pandas: loc[], iloc[] for selection
Pandas: Boolean filtering, sort_values(), groupby()

## Dataset Description

- **Dataset:** Iris (loaded from datasets/iris.csv)
- **Records:** 150 flowers (50 per species)
- **Features:** sepal length, sepal width, petal length, petal width
- **Target:** species (setosa, versicolor, virginica)

## Conclusion

Fundamental NumPy and Pandas operations successfully demonstrated. NumPy enables fast vectorized numerical computation with arrays. Pandas provides powerful data manipulation through DataFrames — loading CSV data, handling missing values, filtering with boolean conditions, sorting, and grouping. These operations form the foundation for all subsequent data science and machine learning tasks.